import React, { createContext, useState, useContext, useEffect } from 'react';

const _SH_LANG = "SaifHany::LanguageEngine";

const translations = {
  en: {
    welcome: "Welcome to Aura",
    products: "Premium Selection",
    special: "Exclusive For You",
    admin: "Aura Control Center",
    no_products: "Inventory Empty",
    buy: "Shop Now",
    add_to_cart: "Add to Cart",
    search: "Search for premium products...",
    categories: "Categories",
    cart: "Your Cart",
    checkout: "Proceed to Checkout",
    total: "Total",
    empty_cart: "Your cart is waiting",
    close: "Close",
    profile: "Profile & Settings",
    logout: "Sign Out",
    save: "Save Changes",
    saving: "Processing...",
    settings: "Settings",
    language: "Language",
    country_change: "Change Region",
    orders: "Order History",
    no_orders: "No recent orders",
    personal_info: "Personal Information",
    full_name: "Full Name",
    see_all: "View All",
    sign_in: "Sign In securely",
    sign_up: "Create Account",
    processing: "Authenticating...",
    or: "OR",
    google: "Continue with Google",
    email: "Email Address",
    password: "Password",
    welcome_back: "Welcome Back",
    create_account: "Join Aura Premium",
    enter_details: "Securely enter your credentials",
    join_community: "Experience world-class shopping",
    no_account: "New to Aura?",
    have_account: "Already a member?",
    description: "Product Description",
    reviews: "reviews",
    add_product: "Add New Product",
    product_name: "Product Name",
    price: "Price",
    cancel: "Cancel",
    inventory_empty: "Warehouse Empty",
    start_adding: "Deploy your first premium product",
    users: "Customer Base",
    name: "Name",
    actions: "Actions",
    ai_engine: "Aura AI Enhancement Engine",
    auto_bg: "AI Background Removal",
    auto_quality: "AI Quality Upscaling",
    ai_processing: "Neural Engine Processing...",
    upload_image: "Drag & drop or click to upload",
    countries_available: "Regional Availability",
    global_all: "Global Delivery",
    account_settings: "Account Preferences",
    region: "Region & Localization",
    dashboard: "Admin Dashboard",
    analytics: "Global Analytics",
    total_products: "Active Products",
    total_users: "Registered Users",
    total_revenue: "Gross Revenue",
    recent_activity: "Recent Global Activity",
    exact_location: "Exact Map Location",
    select_location: "Pinpoint Location",
    phone: "Phone Number",
    whatsapp: "WhatsApp Number",
    governorate: "Governorate / State",
    city: "City",
    address_details: "Street Address / Village",
    order_placed: "Order Placed Successfully",
    order_id: "Order ID",
    discount: "Discount %",
    apply_discount: "Apply Discount",
    delivery_address: "Delivery Address",
    manage_orders: "Manage Orders",
    status: "Status",
    pending: "Pending",
    shipped: "Shipped",
    delivered: "Delivered",
    map_instruction: "Click on the map to set your exact delivery coordinates.",
    link_copied: "Link copied!"
  },
  "ar-EG": {
    welcome: "مرحباً بك في أورا",
    products: "مختارات مميزة",
    special: "حصرياً لك",
    admin: "مركز تحكم أورا",
    no_products: "المخزون فارغ",
    buy: "تسوق الآن",
    add_to_cart: "أضف للسلة",
    search: "ابحث عن منتجات فاخرة...",
    categories: "التصنيفات",
    cart: "سلة التسوق",
    checkout: "إتمام الشراء",
    total: "الإجمالي",
    empty_cart: "سلتك في انتظارك",
    close: "إغلاق",
    profile: "الملف الشخصي",
    logout: "تسجيل الخروج",
    save: "حفظ التغييرات",
    saving: "جاري المعالجة...",
    settings: "الإعدادات",
    language: "اللغة",
    country_change: "تغيير المنطقة",
    orders: "سجل الطلبات",
    no_orders: "لا توجد طلبات حديثة",
    personal_info: "المعلومات الشخصية",
    full_name: "الاسم الكامل",
    see_all: "عرض الكل",
    sign_in: "تسجيل دخول آمن",
    sign_up: "إنشاء حساب",
    processing: "جاري المصادقة...",
    or: "أو",
    google: "المتابعة باستخدام جوجل",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    welcome_back: "مرحباً بعودتك",
    create_account: "انضم إلى أورا المميزة",
    enter_details: "أدخل بياناتك بأمان",
    join_community: "استمتع بتجربة تسوق عالمية",
    no_account: "جديد في أورا؟",
    have_account: "عضو بالفعل؟",
    description: "وصف المنتج",
    reviews: "تقييمات",
    add_product: "إضافة منتج جديد",
    product_name: "اسم المنتج",
    price: "السعر",
    cancel: "إلغاء",
    inventory_empty: "المستودع فارغ",
    start_adding: "أضف أول منتج مميز",
    users: "قاعدة العملاء",
    name: "الاسم",
    actions: "إجراءات",
    ai_engine: "محرك أورا للذكاء الاصطناعي",
    auto_bg: "إزالة الخلفية بالذكاء الاصطناعي",
    auto_quality: "تحسين الجودة بالذكاء الاصطناعي",
    ai_processing: "جاري المعالجة العصبية...",
    upload_image: "اسحب وأفلت أو اضغط للرفع",
    countries_available: "التوفر الإقليمي",
    global_all: "توصيل عالمي",
    account_settings: "تفضيلات الحساب",
    region: "المنطقة والتوطين",
    dashboard: "لوحة تحكم الإدارة",
    analytics: "التحليلات العالمية",
    total_products: "المنتجات النشطة",
    total_users: "المستخدمين المسجلين",
    total_revenue: "إجمالي الإيرادات",
    recent_activity: "النشاط العالمي الأخير",
    exact_location: "الموقع الدقيق على الخريطة",
    select_location: "تحديد الموقع",
    phone: "رقم الهاتف",
    whatsapp: "رقم الواتساب",
    governorate: "المحافظة",
    city: "المدينة / المركز",
    address_details: "تفاصيل العنوان / القرية",
    order_placed: "تم تقديم الطلب بنجاح",
    order_id: "رقم الطلب",
    discount: "نسبة الخصم %",
    apply_discount: "تطبيق الخصم",
    delivery_address: "عنوان التوصيل",
    manage_orders: "إدارة الطلبات",
    status: "الحالة",
    pending: "قيد الانتظار",
    shipped: "تم الشحن",
    delivered: "تم التوصيل",
    map_instruction: "اضغط على الخريطة لتحديد إحداثيات التوصيل الدقيقة.",
    link_copied: "تم نسخ الرابط!"
  },
  "ar-SA": {
    welcome: "حياك الله في أورا",
    products: "مختارات مميزة لك",
    special: "حصرياً لك",
    admin: "مركز تحكم أورا",
    no_products: "المخزون فاضي",
    buy: "تسوق الحين",
    add_to_cart: "أضف للسلة",
    search: "ابحث عن منتجات فاخرة...",
    categories: "الأقسام",
    cart: "سلة التسوق",
    checkout: "ادفع الحين",
    total: "المجموع",
    empty_cart: "سلتك فاضية",
    close: "إغلاق",
    profile: "الملف الشخصي",
    logout: "تسجيل الخروج",
    save: "حفظ التغييرات",
    saving: "جاري المعالجة...",
    settings: "الإعدادات",
    language: "اللغة",
    country_change: "تغيير المنطقة",
    orders: "سجل الطلبات",
    no_orders: "ما عندك طلبات للآن",
    personal_info: "المعلومات الشخصية",
    full_name: "الاسم الكامل",
    see_all: "عرض الكل",
    sign_in: "تسجيل دخول آمن",
    sign_up: "إنشاء حساب",
    processing: "جاري المصادقة...",
    or: "أو",
    google: "المتابعة باستخدام جوجل",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    welcome_back: "مرحباً بعودتك",
    create_account: "انضم إلى أورا المميزة",
    enter_details: "أدخل بياناتك بأمان",
    join_community: "استمتع بتجربة تسوق عالمية",
    no_account: "جديد في أورا؟",
    have_account: "عضو بالفعل؟",
    description: "وصف المنتج",
    reviews: "تقييمات",
    add_product: "إضافة منتج جديد",
    product_name: "اسم المنتج",
    price: "السعر",
    cancel: "إلغاء",
    inventory_empty: "المستودع فاضي",
    start_adding: "أضف أول منتج مميز",
    users: "قاعدة العملاء",
    name: "الاسم",
    actions: "إجراءات",
    ai_engine: "محرك أورا للذكاء الاصطناعي",
    auto_bg: "إزالة الخلفية بالذكاء الاصطناعي",
    auto_quality: "تحسين الجودة بالذكاء الاصطناعي",
    ai_processing: "جاري المعالجة العصبية...",
    upload_image: "اسحب وأفلت أو اضغط للرفع",
    countries_available: "التوفر الإقليمي",
    global_all: "توصيل عالمي",
    account_settings: "تفضيلات الحساب",
    region: "المنطقة والتوطين",
    dashboard: "لوحة تحكم الإدارة",
    analytics: "التحليلات العالمية",
    total_products: "المنتجات النشطة",
    total_users: "المستخدمين المسجلين",
    total_revenue: "إجمالي الإيرادات",
    recent_activity: "النشاط العالمي الأخير",
    exact_location: "الموقع الدقيق على الخريطة",
    select_location: "تحديد الموقع",
    phone: "رقم الجوال",
    whatsapp: "رقم الواتساب",
    governorate: "المنطقة",
    city: "المدينة / الحي",
    address_details: "تفاصيل العنوان",
    order_placed: "تم تقديم الطلب بنجاح",
    order_id: "رقم الطلب",
    discount: "نسبة الخصم %",
    apply_discount: "تطبيق الخصم",
    delivery_address: "عنوان التوصيل",
    manage_orders: "إدارة الطلبات",
    status: "الحالة",
    pending: "قيد الانتظار",
    shipped: "تم الشحن",
    delivered: "تم التوصيل",
    map_instruction: "اضغط على الخريطة لتحديد إحداثيات التوصيل الدقيقة.",
    link_copied: "تم نسخ الرابط!"
  },
  "ar-AE": {
    welcome: "مرحبابك في أورا",
    products: "مختارات مميزة",
    special: "حصرياً لك",
    admin: "مركز تحكم أورا",
    no_products: "المخزون فاضي",
    buy: "تسوق ألحين",
    add_to_cart: "ضيف للسلة",
    search: "دور على منتجات فاخرة...",
    categories: "الأقسام",
    cart: "سلة المشتريات",
    checkout: "الدفع",
    total: "الإجمالي",
    empty_cart: "سلتك فاضية",
    close: "إغلاق",
    profile: "الملف الشخصي",
    logout: "تسجيل الخروج",
    save: "حفظ التغييرات",
    saving: "جاري المعالجة...",
    settings: "الإعدادات",
    language: "اللغة",
    country_change: "تغيير المنطقة",
    orders: "سجل الطلبات",
    no_orders: "ما شي طلبات للحين",
    personal_info: "المعلومات الشخصية",
    full_name: "الاسم الكامل",
    see_all: "عرض الكل",
    sign_in: "تسجيل دخول آمن",
    sign_up: "إنشاء حساب",
    processing: "جاري المصادقة...",
    or: "أو",
    google: "المتابعة باستخدام جوجل",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    welcome_back: "مرحباً بعودتك",
    create_account: "انضم إلى أورا المميزة",
    enter_details: "أدخل بياناتك بأمان",
    join_community: "استمتع بتجربة تسوق عالمية",
    no_account: "جديد في أورا؟",
    have_account: "عضو بالفعل؟",
    description: "وصف المنتج",
    reviews: "تقييمات",
    add_product: "إضافة منتج جديد",
    product_name: "اسم المنتج",
    price: "السعر",
    cancel: "إلغاء",
    inventory_empty: "المستودع فاضي",
    start_adding: "أضف أول منتج مميز",
    users: "قاعدة العملاء",
    name: "الاسم",
    actions: "إجراءات",
    ai_engine: "محرك أورا للذكاء الاصطناعي",
    auto_bg: "إزالة الخلفية بالذكاء الاصطناعي",
    auto_quality: "تحسين الجودة بالذكاء الاصطناعي",
    ai_processing: "جاري المعالجة العصبية...",
    upload_image: "اسحب وأفلت أو اضغط للرفع",
    countries_available: "التوفر الإقليمي",
    global_all: "توصيل عالمي",
    account_settings: "تفضيلات الحساب",
    region: "المنطقة والتوطين",
    dashboard: "لوحة تحكم الإدارة",
    analytics: "التحليلات العالمية",
    total_products: "المنتجات النشطة",
    total_users: "المستخدمين المسجلين",
    total_revenue: "إجمالي الإيرادات",
    recent_activity: "النشاط العالمي الأخير",
    exact_location: "الموقع الدقيق على الخريطة",
    select_location: "تحديد الموقع",
    phone: "رقم الموبايل",
    whatsapp: "رقم الواتساب",
    governorate: "الإمارة",
    city: "المدينة / المنطقة",
    address_details: "تفاصيل العنوان",
    order_placed: "تم تقديم الطلب بنجاح",
    order_id: "رقم الطلب",
    discount: "نسبة الخصم %",
    apply_discount: "تطبيق الخصم",
    delivery_address: "عنوان التوصيل",
    manage_orders: "إدارة الطلبات",
    status: "الحالة",
    pending: "قيد الانتظار",
    shipped: "تم الشحن",
    delivered: "تم التوصيل",
    map_instruction: "اضغط على الخريطة لتحديد إحداثيات التوصيل الدقيقة.",
    link_copied: "تم نسخ الرابط!"
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem('aura_lang') || 'en');
  const [country, setCountry] = useState(() => {
    const saved = localStorage.getItem('aura_country');
    return saved ? JSON.parse(saved) : null;
  });

  const updateLang = (newLang) => {
    setLang(newLang);
    localStorage.setItem('aura_lang', newLang);
    document.documentElement.dir = newLang === 'ar' ? 'rtl' : 'ltr';
  };

  const updateCountry = (newCountryObj) => {
    setCountry(newCountryObj);
    if (newCountryObj) {
      localStorage.setItem('aura_country', JSON.stringify(newCountryObj));
      if (newCountryObj.lang) updateLang(newCountryObj.lang);
    } else {
      localStorage.removeItem('aura_country');
    }
  };

  useEffect(() => {
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
  }, [lang]);

  const translate = (key) => {
    if (lang === 'ar') {
      const dialect = country?.code === 'SA' ? 'ar-SA' : country?.code === 'AE' ? 'ar-AE' : 'ar-EG';
      return (translations[dialect] && translations[dialect][key]) || translations['en'][key] || key;
    }
    const fallback = translations['en'][key] || key;
    return (translations[lang] && translations[lang][key]) || fallback;
  };

  const formatPrice = (price) => {
    if (!country || !country.currency) return `$${Number(price).toFixed(2)}`;
    const rate = country.exchangeRate || 1;
    const converted = Number(price) * rate;
    return new Intl.NumberFormat(lang === 'ar' ? 'ar-EG' : 'en-US', {
      style: 'currency',
      currency: country.currency
    }).format(converted);
  };

  return (
    <LanguageContext.Provider value={{ 
      lang, 
      setLang: updateLang, 
      translate, 
      country, 
      setCountry: updateCountry,
      formatPrice
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
export const _fingerprint_lang = _SH_LANG;
